import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav id="navbar">
          <Link href="/">Logo</Link>
          <ul>
            <Link href="/prices">Prices</Link>
            <Link href="/map">Map Information</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
